-- Create Table

CREATE TABLE IF NOT EXISTS MY_TABLE(
  ID SERIAL PRIMARY KEY,
  NAME TEXT NOT NULL UNIQUE,
  AGE INTEGER NOT NULL CHECK (AGE<=20),
  SALARY DECIMAL(10,2) NOT NULL,
  COURSEWORK VARCHAR(266) NOT NULL,
  COLLEGE TEXT NOT NULL,
  PASSED BOOLEAN DEFAULT TRUE
);

-- INSERT

INSERT INTO MY_TABLE (NAME, AGE, SALARY, COURSEWORK, COLLEGE, PASSED) 
VALUES ('John D', 18, 2500.00, 'Computer Science', 'ABC University', TRUE);

-- SELECT

SELECT * FROM my_table;

-- ALTER
ALTER TABLE my_table DROP COLUMN NEW_COLUMN;
ALTER TABLE my_table ADD COLUMN NEW_COLUMN VARCHAR(200);
ALTER TABLE my_table ADD CONSTRAINT my_table_pk PRIMARY KEY (NEW_COLUMN);
ALTER TABLE my_table RENAME COLUMN NEW_COLUMN TO NEW_COLUMN_TWO;
ALTER TABLE my_table DROP CONSTRAINT my_table_pk;
ALTER TABLE my_table ADD CONSTRAINT my_table_fk FOREIGN KEY (column_name) REFERENCES other_table(other_column);
ALTER TABLE my_table DROP CONSTRAINT my_table_fk;
ALTER TABLE my_table ALTER COLUMN NAME SET DEFAULT 'RAMESH';
ALTER TABLE my_table ALTER COLUMN NAME DROP DEFAULT;

-- Distinct
SELECT DISTINCT name FROM my_table;

-- Order by
SELECT age FROM my_table ORDER BY age ASC;

-- AND OR NOT
SELECT * FROM my_table WHERE AGE=10 OR AGE=12;
SELECT * FROM my_table WHERE AGE BETWEEN 10 AND 12;
SELECT * FROM my_table WHERE AGE IS NOT NULL;
SELECT * FROM my_table WHERE AGE IS NULL;
SELECT * FROM my_table WHERE AGE NOT BETWEEN 10 AND 12;
SELECT * FROM my_table WHERE NOT AGE>12;
SELECT * FROM my_table WHERE NOT AGE IN (10,12,3);

-- Update
UPDATE my_table SET AGE=13 WHERE id=1;
UPDATE my_table SET AGE=1;  --(set for all)

-- Delete
DELETE FROM my_table WHERE AGE=10;
DELETE FROM my_table; --(delete all)

-- Limit Offset and TOP ETC
SELECT * FROM my_table LIMIT 2 OFFSET 1;
SELECT * FROM my_table FETCH FIRST 3 ROWS ONLY;

-- AGGREGATION

SELECT COUNT(*) FROM my_table;
SELECT SUM(age) FROM my_table;
SELECT MIN(age) FROM my_table;
SELECT MAX(age) FROM my_table;
SELECT AVG(age) FROM my_table;
SELECT COUNT(DISTINCT age) FROM my_table;
