-- Create Table

CREATE TABLE IF NOT EXISTS MY_TABLE(
  ID SERIAL PRIMARY KEY,
  NAME TEXT NOT NULL UNIQUE,
  AGE INTEGER NOT NULL CHECK (AGE<=20),
  SALARY DECIMAL(10,2) NOT NULL,
  COURSEWORK VARCHAR(266) NOT NULL,
  COLLEGE TEXT NOT NULL,
  PASSED BOOLEAN DEFAULT TRUE
);

-- INSERT

INSERT INTO MY_TABLE (NAME, AGE, SALARY, COURSEWORK, COLLEGE, PASSED) 
VALUES ('John D', 18, 2500.00, 'Computer Science', 'ABC University', TRUE);

-- SELECT

SELECT * FROM my_table;

-- ALTER
ALTER TABLE my_table DROP COLUMN NEW_COLUMN;
ALTER TABLE my_table ADD COLUMN NEW_COLUMN VARCHAR(200);
